### ISSUE TITLE
Windows path issues... again

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2602]
### Describe the bug
See this stack trace:
```
[Errno 2] No such file or directory: 'target\\compiled\\dbt_project\\models\\amp\\04_raw\\source_performance_media_imports_fivetran_netsuite_mapping.yml\\schema_test\\source_not_null_performance-media-imports_fivetran_netsuite_mapping_companies_mapping_netsuite_company_id.sql'
2020-06-30 07:52:45.975033 (Thread-4): 
Traceback (most recent call last):
  File "c:\users\dbt_user\anaconda3\envs\dbt_windows\lib\site-packages\dbt\node_runners.py", line 228, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "c:\users\dbt_user\anaconda3\envs\dbt_windows\lib\site-packages\dbt\node_runners.py", line 165, in compile_and_execute
    ctx.node = self.compile(manifest)
  File "c:\users\dbt_user\anaconda3\envs\dbt_windows\lib\site-packages\dbt\node_runners.py", line 340, in compile
    return compile_node(self.adapter, self.config, self.node, manifest, {})
  File "c:\users\dbt_user\anaconda3\envs\dbt_windows\lib\site-packages\dbt\compilation.py", line 264, in compile_node
    node.injected_sql
  File "c:\users\dbt_user\anaconda3\envs\dbt_windows\lib\site-packages\dbt\contracts\graph\parsed.py", line 172, in write_node
    write_file(full_path, payload)
  File "c:\users\dbt_user\anaconda3\envs\dbt_windows\lib\site-packages\dbt\clients\system.py", line 136, in write_file
    with open(path, 'w', encoding='utf-8') as f:
```

### Steps To Reproduce
Must have something to do with the Windows/python version at play?? TBD, working on getting more info.

### Expected behavior
dbt should log a debug log line for the exception and move on without error

**The output of `dbt --version`:**
```
0.17.0-rc2
```

**The operating system you're using:** Windows (version TBD)

**The output of `python --version`:** TBD

**Comment by beckjake** [comment]
😡 :rage1: :rage2: :rage3: :rage4: there are not enough rage emojis for how I feel about this

**Comment by drewbanin** [comment]
closed by https://github.com/fishtown-analytics/dbt/pull/2603
