### ISSUE TITLE
Column documentation fails with particular string

### ISSUE THREAD

**Issue by Limess** [fishtown-analytics/dbt#2637]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?
DBT fails to add a comment to the following column:

`comment on column "analytics"."analyst_charlie_briggs_scratch"."dim_reports".schedule_frequency, is $dbt_comment_literal_block$The frequency type of the schedule, e.g. 'daily' Some adapted legacy alerts did not have a schedule in which case this is taken from their `frequency_type`
$dbt_comment_literal_block$;`

```
2020-07-21 09:12:06.852563 (Thread-3): Postgres error: syntax error at or near ","
LINE 24: ...e_briggs_scratch"."dim_reports".schedule_frequency, is $dbt_...
                                                              ^

2020-07-21 09:12:06.852975 (Thread-3): On model.signal_dbt.dim_reports: ROLLBACK
2020-07-21 09:12:06.955836 (Thread-3): finished collecting timing info
2020-07-21 09:12:06.958338 (Thread-3): Database Error in model dim_reports (models/marts/core/dim_reports.sql)
  syntax error at or near ","
  LINE 24: ...e_briggs_scratch"."dim_reports".schedule_frequency, is $dbt_...
                                                                ^
  compiled SQL at target/run/signal_dbt/models/marts/core/dim_reports.sql
Traceback (most recent call last):
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/adapters/postgres/connections.py", line 46, in exception_handler
    yield
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/adapters/sql/connections.py", line 74, in add_query
    cursor.execute(sql, bindings)
psycopg2.errors.SyntaxError: syntax error at or near ","
LINE 24: ...e_briggs_scratch"."dim_reports".schedule_frequency, is $dbt_...
                                                              ^
```

### Steps To Reproduce

Add a model to a project running against Redshift with the config:

```
    +persist_docs:
      relations: true
      columns: true
```

Add a model called `dim_reports` with a column `schedule_frequency`.

Add the schema file:
```
  - name: dim_reports
    columns:
      - name: schedule_frequency,
        description: >
          The frequency type of the schedule, e.g. 'daily'
          Some adapted legacy alerts did not have a schedule in which case this is taken from their `frequency_type`
```

run `dbt run` with the above model.

### Expected behavior
I'd expect either the comment to be validated and fail fast, or a better error message indicating why the error occured.

It's relatively difficult to debug this as the line numbers in the DBT log don't correspond to anything in the `target` directory.

### Screenshots and log output

The above exception was the direct cause of the following exception:

```
Traceback (most recent call last):
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/node_runners.py", line 228, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/node_runners.py", line 171, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/node_runners.py", line 273, in run
    return self.execute(compiled_node, manifest)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/node_runners.py", line 459, in execute
    result = MacroGenerator(materialization_macro, context)()
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/clients/jinja.py", line 327, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/clients/jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 81, in macro
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/clients/jinja.py", line 327, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/clients/jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 26, in macro
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/clients/jinja.py", line 327, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/clients/jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 96, in macro
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/clients/jinja.py", line 327, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/clients/jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 49, in macro
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/clients/jinja.py", line 327, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/clients/jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 33, in macro
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/clients/jinja.py", line 327, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/clients/jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 41, in macro
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/adapters/base/impl.py", line 228, in execute
    fetch=fetch
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/adapters/sql/connections.py", line 119, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/adapters/sql/connections.py", line 82, in add_query
    return connection, cursor
  File "/Users/charlie.briggs/.pyenv/versions/3.7.6/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/charlie.briggs/Projects/signal/analytics/dbt/.venv/lib/python3.7/site-packages/dbt/adapters/postgres/connections.py", line 58, in exception_handler
    raise dbt.exceptions.DatabaseException(str(e).strip()) from e
dbt.exceptions.DatabaseException: Database Error in model dim_reports (models/marts/core/dim_reports.sql)
  syntax error at or near ","
  LINE 24: ...e_briggs_scratch"."dim_reports".schedule_frequency, is $dbt_...
                                                                ^
  compiled SQL at target/run/signal_dbt/models/marts/core/dim_reports.sql
2020-07-21 09:12:06.962021 (Thread-3): 10:12:06 | 138 of 183 ERROR creating table model analyst_charlie_briggs_scratch.dim_reports [ERROR in 310.07s]
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.17.1
   latest version: 0.17.1

Up to date!

Plugins:
  - redshift: 0.17.1
  - postgres: 0.17.1
```

**The operating system you're using:**

Mac OS 10.15.6 (19G73)

**The output of `python --version`:**

3.7.6

**Comment by Limess** [comment]
Aha! This is entirely me missing the blindingly obvious column name being `schedule_frequency,` in the schema file. I'm closing this as it's a user error.
