### ISSUE TITLE
Failed DBT Install with Brew, Success with Pip, But DBT Throws Errors

### ISSUE THREAD

**Issue by jkellogg1998** [fishtown-analytics/dbt#3107]
### Describe the bug
I used `brew install dbt` a few times and it would run for awhile and then blow up at the end with a half-page full of errors.  I then tried pip and couldn't get that to work, finally tried `python3 -m pip install dbt` and that ran all the way through!  The problem now is when I try a dbt command I get an error log every time. The same error log no matter the command.

To me it feels like DBT needs to use a recent version of Python but this old 2.7 version, which I'm not sure how it got there and I don't need, may be interfering? I never overtly installed any versions of Python but somehow I seem to have acquired 3. Just a guess.

### Expected behavior
If I type "dbt --version" I expect to simply see the version.  Instead I get an error log.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: _None yet__)

**The output of `dbt --version`:**
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/dbt", line 5, in <module>
    from dbt.main import main
  File "/opt/homebrew/lib/python3.9/site-packages/dbt/main.py", line 11, in <module>
    import dbt.version
  File "/opt/homebrew/lib/python3.9/site-packages/dbt/version.py", line 100, in <module>
    installed = get_installed_version()
  File "/opt/homebrew/lib/python3.9/site-packages/dbt/version.py", line 29, in get_installed_version
    return dbt.semver.VersionSpecifier.from_version_string(__version__)
  File "/opt/homebrew/lib/python3.9/site-packages/dbt/semver.py", line 100, in from_version_string
    return cls.from_dict(matched)
  File "/opt/homebrew/lib/python3.9/site-packages/hologram/__init__.py", line 618, in from_dict
    cls.validate(data)
  File "/opt/homebrew/lib/python3.9/site-packages/hologram/__init__.py", line 957, in validate
    schema = _validate_schema(cls)
  File "/opt/homebrew/lib/python3.9/site-packages/hologram/__init__.py", line 183, in _validate_schema
    schema = schema_cls.json_schema()
  File "/opt/homebrew/lib/python3.9/site-packages/hologram/__init__.py", line 942, in json_schema
    return cls._json_schema_recursive(
  File "/opt/homebrew/lib/python3.9/site-packages/hologram/__init__.py", line 913, in _json_schema_recursive
    schema = cls._schema_defs_from_cache(definitions)
  File "/opt/homebrew/lib/python3.9/site-packages/hologram/__init__.py", line 900, in _schema_defs_from_cache
    schema = cls._collect_json_schema(definitions)
  File "/opt/homebrew/lib/python3.9/site-packages/hologram/__init__.py", line 863, in _collect_json_schema
    properties[target_field], is_required = cls._get_field_schema(
  File "/opt/homebrew/lib/python3.9/site-packages/hologram/__init__.py", line 809, in _get_field_schema
    field_schema, required = cls._get_schema_for_type(
  File "/opt/homebrew/lib/python3.9/site-packages/hologram/__init__.py", line 783, in _get_schema_for_type
    raise ValidationError(f"Unable to create schema for '{type_name}'")
hologram.ValidationError: Unable to create schema for 'Optional'
```

**The operating system you're using:**
Big Sur 11.0.1

**The output of `python --version`:**
Python 2.7.16

### Additional context
`brew list | grep python`
python@3.8
python@3.9

Even though Homebrew ran for awhile trying to install dbt I thought I'd try to get rid of it and I get this:
`brew uninstall dbt`
Error: No available formula or cask with the name "dbt".

**Comment by jtcohen6** [comment]
Hey @jkellogg1998!

Based on the error message, it appears that your `python3` is using python 3.9. You can confirm this by running:
```bash
$ python3 --version
```

The latest version of dbt v0.19.0 has full support for python 3.6, 3.7, and 3.8. You can try [reinstalling](https://github.com/Homebrew/homebrew-core/issues/62911#issuecomment-713127246) or [relinking python](https://stackoverflow.com/questions/60453261/how-to-default-python3-8-on-my-mac-using-homebrew) to use `python@3.8` (installed via brew) instead of python 3.9:
```bash
# reinstall
$ brew reinstall python@3.8

# or relink
$ brew unlink python@3.8
$ brew link --force python@3.8
```

If you _do_ know which adapter you're planning to use, and it's not Snowflake, you can install that specific adapter in a py3.9 environment. This doesn't work for dbt-snowflake because of some dependencies of the Snowflake python connector.
```bash
$ pip install dbt-postgres
```

FYI: This isn't the best place for installation help. If you're working out the quirks of your local system or python env, [StackOverflow](https://stackoverflow.com/tags/dbt) is going to be more helpful (and likely someone has already experienced your same issue, or similar). If you believe there is a bug with dbt, making it impossible or exceedingly difficult to install, then opening an issue in the `dbt` repo is the right move.
