### ISSUE TITLE
commenting out schema tests produces compilation errors

### ISSUE THREAD

**Issue by jthandy** [fishtown-analytics/dbt#328]
using standard yml comment syntax (`#`), running a dbt compile gives me the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/dbt", line 11, in <module>
    load_entry_point('dbt==0.7.1', 'console_scripts', 'dbt')()
  File "/usr/local/Cellar/dbt/HEAD-e060aeb/libexec/lib/python3.6/site-packages/dbt/main.py", line 31, in main
    handle(args)
  File "/usr/local/Cellar/dbt/HEAD-e060aeb/libexec/lib/python3.6/site-packages/dbt/main.py", line 49, in handle
    res = run_from_args(parsed)
  File "/usr/local/Cellar/dbt/HEAD-e060aeb/libexec/lib/python3.6/site-packages/dbt/main.py", line 103, in run_from_args
    result = task.run()
  File "/usr/local/Cellar/dbt/HEAD-e060aeb/libexec/lib/python3.6/site-packages/dbt/task/run.py", line 18, in run
    self.project, self.args)
  File "/usr/local/Cellar/dbt/HEAD-e060aeb/libexec/lib/python3.6/site-packages/dbt/compilation.py", line 52, in compile_and_print_status
    results.update(compiler.compile())
  File "/usr/local/Cellar/dbt/HEAD-e060aeb/libexec/lib/python3.6/site-packages/dbt/compilation.py", line 546, in compile
    macro_generator)
  File "/usr/local/Cellar/dbt/HEAD-e060aeb/libexec/lib/python3.6/site-packages/dbt/compilation.py", line 523, in load_all_nodes
    self.get_parsed_schema_tests(root_project, all_projects))
  File "/usr/local/Cellar/dbt/HEAD-e060aeb/libexec/lib/python3.6/site-packages/dbt/compilation.py", line 508, in get_parsed_schema_tests
    relative_dirs=project.get('source-paths', [])))
  File "/usr/local/Cellar/dbt/HEAD-e060aeb/libexec/lib/python3.6/site-packages/dbt/parser.py", line 369, in load_and_parse_yml
    return parse_schema_tests(result, root_project, all_projects)
  File "/usr/local/Cellar/dbt/HEAD-e060aeb/libexec/lib/python3.6/site-packages/dbt/parser.py", line 259, in parse_schema_tests
    for config in configs:
TypeError: 'NoneType' object is not iterable
```

**Comment by cmcarthur** [comment]
@jthandy can you send me the file?

**Comment by cmcarthur** [comment]
fix with test: https://github.com/fishtown-analytics/dbt/pull/330

**Comment by cmcarthur** [comment]
fix is in development
