### ISSUE TITLE
dbt is not able to fetch error message from BigQuery via oauth

### ISSUE THREAD

**Issue by Kreshu** [fishtown-analytics/dbt#3411]
### Describe the bug

I am having issues with dbt and BQ setup. In general everything works fine, but when BQ returns an error due to failing SQL, dbt CLI is not able to fetch error from BQ:
```
▶ dbt run --models asset.dda.global_dda_dv
Running with dbt=0.19.1
...
18:37:34 | Concurrency: 1 threads (target='dev')
18:37:34 |
18:37:34 | 1 of 1 START view model dbt_bart.global_dda_dv....................... [RUN]
18:37:35 | 1 of 1 ERROR creating view model dbt_bart.global_dda_dv.............. [ERROR in 1.27s]
18:37:35 |
18:37:35 | Finished running 1 view model in 3.85s.
Completed with 1 error and 0 warnings:
Runtime Error in model global_dda_dv (models/asset/dda/global_dda_dv.sql)
  404 GET https://bigquery.googleapis.com/bigquery/v2/projects/project-xyz/queries/8b5ace67-828a-4328-88d1-4c0ebb8b67e8?maxResults=0&location=EU&prettyPrint=false: Not found: Job project-xyz:EU.8b5ace67-828a-4328-88d1-4c0ebb8b67e8
  (job ID: 8b5ace67-828a-4328-88d1-4c0ebb8b67e8)
Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

In the same time, this particular error I am able to get with `bq show -j <job_id>`.
I am using OAuth via gcloud for authorisation, here’s my config:
```
dde-dbt: # this needs to match the profile: in your dbt_project.yml file
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: project-xyz
      dataset: dbt_bart
      threads: 1
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1
```
### Steps To Reproduce

1. Configure local environment to connect with BigQuery through oauth
2. Execute `dbt run` with failing SQL model
3. dbt is not able to retrieve error message from BigQuery

### Expected behavior

dbt CLI should be able to find BQ job and fetch error message

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other

**The output of `dbt --version`:**
```
installed version: 0.19.1
   latest version: 0.19.1

Up to date!

Plugins:
  - bigquery: 0.19.1
  - snowflake: 0.19.1
  - redshift: 0.19.1
  - postgres: 0.19.1
```

**The operating system you're using:** macOS Catalina 10.15.7

**The output of `python --version`:** Python 3.7.3

**Comment by Kreshu** [comment]
@jtcohen6 thanks for picking this up so quickly! Here's a stacktrace:
```
2021-06-01 10:40:27.235575 (Thread-1): Runtime Error in model global_dda_dv (models/asset/dda/global_dda_dv.sql)
  404 GET https://bigquery.googleapis.com/bigquery/v2/projects/project-xyz/queries/5bf34910-93fd-4fb3-a203-b2ad04fa466f?maxResults=0&location=EU&prettyPrint=false: Not found: Job project-xyz:EU.5bf34910-93fd-4fb3-a203-b2ad04fa466f
  (job ID: 5bf34910-93fd-4fb3-a203-b2ad04fa466f)
Traceback (most recent call last):
  File "/usr/local/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/dbt/adapters/bigquery/connections.py", line 149, in exception_handler
    yield
  File "/usr/local/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/dbt/adapters/bigquery/connections.py", line 534, in _retry_and_handle
    return retry.retry_target(
  File "/usr/local/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/dbt/adapters/bigquery/connections.py", line 327, in fn
    return self._query_and_results(client, sql, conn, job_params)
  File "/usr/local/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/dbt/adapters/bigquery/connections.py", line 520, in _query_and_results
    iterator = query_job.result(timeout=timeout)
  File "/usr/local/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1146, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/usr/local/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 631, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/usr/local/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/google/api_core/future/polling.py", line 129, in result
    self._blocking_poll(timeout=timeout, **kwargs)
  File "/usr/local/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1042, in _blocking_poll
    super(QueryJob, self)._blocking_poll(timeout=timeout, **kwargs)
  File "/usr/local/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/google/api_core/future/polling.py", line 107, in _blocking_poll
    retry_(self._done_or_raise)(**kwargs)
  File "/usr/local/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/usr/local/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/google/api_core/future/polling.py", line 85, in _done_or_raise
    if not self.done(**kwargs):
  File "/usr/local/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1022, in done
    self._query_results = self._client._get_query_results(
  File "/usr/local/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 1557, in _get_query_results
    resource = self._call_api(
  File "/usr/local/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 636, in _call_api
    return call()
  File "/usr/local/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/usr/local/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/usr/local/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/google/cloud/_http.py", line 438, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 GET https://bigquery.googleapis.com/bigquery/v2/projects/project-xyz/queries/5bf34910-93fd-4fb3-a203-b2ad04fa466f?maxResults=0&location=EU&prettyPrint=false: Not found: Job project-xyz:EU.5bf34910-93fd-4fb3-a203-b2ad04fa466f
(job ID: 5bf34910-93fd-4fb3-a203-b2ad04fa466f)
```

**Comment by jtcohen6** [comment]
@Kreshu Thanks for including the full stacktrace. How reliably does this error crop up? Every time you run a model with any SQL errors?

It look like a lot of the handling above is passing between the `good.cloud.bigquery` and `google.api_core` libraries. The last place dbt code is directly involved is `_query_and_results`, called by `raw_execute`:

https://github.com/fishtown-analytics/dbt/blob/1e5a7878e5188fa58f91e2f257041f28fdb948fc/plugins/bigquery/dbt/adapters/bigquery/connections.py#L523-L530

Is it possible we're missing one of the [`job_params`](https://github.com/fishtown-analytics/dbt/blob/1e5a7878e5188fa58f91e2f257041f28fdb948fc/plugins/bigquery/dbt/adapters/bigquery/connections.py#L321-L332) we'd need? Perhaps something to do with dataset/project location?

It sounds like the job is successfully submitted, however, if this works for you:

> In the same time, this particular error I am able to get with `bq show -j <job_id>`.

So it seems like a matter of figuring out why the Google libraries are able to successfully submit a query job, but then they're unable to poll for its result or error message...

**Comment by Kreshu** [comment]
@jtcohen6 yes, it happens every time I have SQL error.
I performed another test - I've changed region to US in `~/.dbt/profiles.yml`, and dbt was able to get the error message
```
▶ dbt run --models asset.dda.global_dda_dv
Running with dbt=0.19.1
...
15:24:50 | Concurrency: 1 threads (target='dev')
15:24:50 |
15:24:50 | 1 of 1 START view model dbt_bart.global_dda_dv....................... [RUN]
15:24:51 | 1 of 1 ERROR creating view model dbt_bart.global_dda_dv.............. [ERROR in 0.74s]
15:24:51 |
15:24:51 | Finished running 1 view model in 3.09s.
Completed with 1 error and 0 warnings:
Runtime Error in model global_dda_dv (models/asset/dda/global_dda_dv.sql)
  404 GET https://bigquery.googleapis.com/bigquery/v2/projects/project-xyz/queries/e1c7d96c-946e-420f-aceb-51e8283c59cc?maxResults=0&location=US&prettyPrint=false: Not found: Project wrong-project
  (job ID: e1c7d96c-946e-420f-aceb-51e8283c59cc)
Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```
So at least we're sure we're on the right track.

FYI I am on vacation starting tomorrow till Monday, so I can be not responsive.
