### ISSUE TITLE
Handle case where dependency download from Github fails

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#451]
Saw one of these in Sinter:

```
Pulling new dependency stripe.
[Errno 2] No such file or directory: 'dbt_modules/stripe'
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/dbt/task/deps.py", line 101, in __pull_deps_recursive
dep_folder = self.__pull_repo(repo, branch)
File "/usr/local/lib/python3.5/dist-packages/dbt/task/deps.py", line 44, in __pull_repo
start_sha = dbt.clients.git.get_current_sha(dependency_path)
File "/usr/local/lib/python3.5/dist-packages/dbt/clients/git.py", line 44, in get_current_sha
out, err = run_cmd(cwd, ['git', 'rev-parse', 'HEAD'])
File "/usr/local/lib/python3.5/dist-packages/dbt/clients/git.py", line 16, in run_cmd
stderr=subprocess.PIPE)
File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
restore_signals, start_new_session)
File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'dbt_modules/stripe'
```

This took three minutes and then exited. Could be related to a Github outage earlier today. In any case, don't stack trace if a pull from Github fails.

**Comment by drewbanin** [comment]
hub site?
