### ISSUE TITLE
dbt 0.10 missing urllib3 dependency for python 2.7.14

### ISSUE THREAD

**Issue by atharvai** [fishtown-analytics/dbt#731]
I installed dbt via pip on Python 2.7.14 on Windows 10. However running `dbt compile....` threw an Import Error:
```ImportError: No module named urllib3.response```
Turns out `urllib3` wasn't installed. Manually running `pip install urllib3` resolved the error. 
Maybe this could be added to setup.py dependencies?

**Comment by atharvai** [comment]
```$ dbt compile --profile fulla-test --models coredata
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\dbt.exe\__main__.py", line 5, in <module>
  File "c:\python27\lib\site-packages\dbt\main.py", line 10, in <module>
    import dbt.project as project
  File "c:\python27\lib\site-packages\dbt\project.py", line 13, in <module>
    import dbt.context.common
  File "c:\python27\lib\site-packages\dbt\context\common.py", line 6, in <module>
    from dbt.adapters.factory import get_adapter
  File "c:\python27\lib\site-packages\dbt\adapters\factory.py", line 6, in <module>
    from dbt.adapters.bigquery import BigQueryAdapter
  File "c:\python27\lib\site-packages\dbt\adapters\bigquery.py", line 18, in <module>
    import google.cloud.bigquery
  File "c:\python27\lib\site-packages\google\cloud\bigquery\__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "c:\python27\lib\site-packages\google\cloud\bigquery\client.py", line 28, in <module>
    from google.resumable_media.requests import MultipartUpload
  File "c:\python27\lib\site-packages\google\resumable_media\requests\__init__.py", line 663, in <module>
    from google.resumable_media.requests.download import ChunkedDownload
  File "c:\python27\lib\site-packages\google\resumable_media\requests\download.py", line 21, in <module>
    import urllib3.response
ImportError: No module named urllib3.response```

Executing from gitbash (mingw64)

**Comment by drewbanin** [comment]
Thanks @atharvai! I'll do some digging around the BigQuery deps here -- this is really helpful.

**Comment by drewbanin** [comment]
@atharvai just merged a fix for this. Feel free to reopen this if you continue to have issues! Think you should be good to go now though :)

**Comment by atharvai** [comment]
:highfive: Thanks for the quick fix!
